import React from 'react';
import { XIcon } from './icons';

interface TermsOfServiceProps {
  onClose: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 bg-primary/80 backdrop-blur-sm flex items-center justify-center z-50">
      <div className="bg-light-secondary dark:bg-secondary rounded-lg shadow-2xl border border-light-accent/50 dark:border-accent/50 w-full max-w-3xl h-[80vh] flex flex-col overflow-hidden">
        <header className="flex items-center justify-between p-4 border-b border-light-accent dark:border-accent shrink-0">
          <h2 className="text-xl font-bold text-light-text-main dark:text-text-main">Terms of Service</h2>
          <button onClick={onClose} className="text-light-text-muted dark:text-gray-400 hover:text-light-text-main dark:hover:text-white transition-colors">
            <XIcon className="w-6 h-6" />
          </button>
        </header>
        <main className="p-6 overflow-y-auto text-light-text-muted dark:text-gray-300">
          <p className="mb-4"><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
          
          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">1. Agreement to Terms</h3>
          <p>By using our application, UF AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the application.</p>

          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">2. Use of the Service</h3>
          <p>UF AI provides access to various third-party artificial intelligence models. You agree to use the service responsibly and in compliance with all applicable laws and regulations. You are responsible for your conduct and all content you submit.</p>
          <p className="mt-2">You agree not to use the service to:</p>
          <ul className="list-disc list-inside ml-4 space-y-2 mt-2">
            <li>Generate content that is unlawful, harmful, threatening, abusive, defamatory, obscene, or otherwise objectionable.</li>
            <li>Impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity.</li>
            <li>Engage in any activity that could damage, disable, overburden, or impair the service or interfere with any other party's use of the service.</li>
            <li>Attempt to gain unauthorized access to any part of the service or its related systems.</li>
          </ul>

          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">3. Accounts</h3>
          <p>When you create an account with us, you must provide information that is accurate, complete, and current at all times. You are responsible for safeguarding the password that you use to access the service and for any activities or actions under your password.</p>

          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">4. Intellectual Property</h3>
          <p>The application and its original content, features, and functionality are and will remain the exclusive property of UF AI and its licensors. You retain ownership of the content you generate through the service. However, by using the service, you grant the respective AI model providers rights to use your input to improve their services, as per their terms.</p>
          
          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">5. Disclaimers and Limitation of Liability</h3>
          <p>The service is provided on an "AS IS" and "AS AVAILABLE" basis. The responses generated by the AI models are for informational and entertainment purposes only and should not be considered as professional advice (e.g., medical, legal, or financial). We do not warrant the accuracy, completeness, or usefulness of any information generated by the AI.</p>
          <p className="mt-2">In no event shall UF AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>
          
          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">6. Termination</h3>
          <p>We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
          
          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">7. Governing Law</h3>
          <p>These Terms shall be governed and construed in accordance with the laws of Pakistan, without regard to its conflict of law provisions.</p>
          
          <h3 className="text-lg font-semibold text-light-text-main dark:text-text-main mt-6 mb-2">8. Changes to Terms</h3>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service within the application. Your continued use of the service after any such changes constitutes your acceptance of the new Terms.</p>
        </main>
      </div>
    </div>
  );
};